apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-sleeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-sleeper
  template:
    metadata:
      labels:
        app: ubuntu-sleeper
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:20.04
          command: [ "bash", "-c", "sleep 3600" ]
          imagePullPolicy: IfNotPresent
